Repository chicken-sloths/bangazon-site-sprint3, pull requests merged in 2018-04, with the labels that each got.

#32 data gen
  data/build-data.js
  data/faker/_customersFaker.js
  data/faker/_ordersFaker.js
  data/faker/_paymentOptionsFaker.js
  data/faker/_productOrdersFaker.js
  data/faker/_productTypesFaker.js
  data/faker/_productsFaker.js
  data/faker/index.js
  data/json/customers.json
  data/json/orders.json
  data/json/paymentOptions.json
  data/json/productOrders.json
  data/json/productTypes.json
  data/json/products.json
  data/randomInt.js
  package-lock.json
  package.json
Labels: dave, david, feature

#45 Kb db gen
  .gitignore
  app/app.js
  app/controllers/authCtrl.js
  app/models/config/config.json
  app/models/config/config.sample.json
  app/models/config/passport-strat.js
  app/models/customer.js
  app/models/index.js
  app/models/order.js
  app/models/paymentoption.js
  app/models/product.js
  app/models/productorder.js
  app/models/producttype.js
  app/models/user.js
  app/routes/authRoute.js
  app/routes/index.js
  app/views/index.pug
  app/views/login.pug
  app/views/partials/nav.pug
  app/views/partials/user-form.pug
  app/views/register.pug
  app/views/welcome.pug
  config/config.json
  data/createDb.js
  data/faker/_customersFaker.js
  data/faker/_ordersFaker.js
  data/faker/_paymentOptionsFaker.js
  data/faker/_productOrdersFaker.js
  data/faker/_productTypesFaker.js
  data/faker/_productsFaker.js
  data/json/customers.json
  data/json/orders.json
  data/json/paymentOptions.json
  data/json/productOrders.json
  data/json/productTypes.json
  data/json/products.json
  data/randomInt.js
  migrations/20180419145202-create-customer.js
  migrations/20180419145403-create-product.js
  migrations/20180419145815-create-payment-option.js
  migrations/20180419151246-create-product-type.js
  migrations/20180419151440-create-order.js
  migrations/20180419151808-create-product-order.js
  package-lock.json
  package.json
Labels: dave, david, melissa

#42 Initializes ctrl-view pairs
  .gitignore
  app/app.js
  app/controllers/cartCtrl.js
  app/controllers/categoryCtrl.js
  app/controllers/completeOrderCtrl.js
  app/controllers/config/config.json
  app/controllers/config/passport-strat.js
  app/controllers/managePaymentsCtrl.js
  app/controllers/manageProductsCtrl.js
  app/controllers/productDetailCtrl.js
  app/controllers/searchCtrl.js
  app/controllers/settingsCtrl.js
  app/models/config/config.json
  app/views/cart.pug
  app/views/category.pug
  app/views/complete-order.pug
  app/views/layout.pug
  app/views/login.pug
  app/views/manage-payments.pug
  app/views/manage-products.pug
  app/views/new-payment-option.pug
  app/views/partials/product-card.pug
  app/views/partials/thanks.pug
  app/views/product-details.pug
  app/views/register.pug
  app/views/search.pug
  app/views/settings.pug
  app/views/welcome.pug
  migrations/models/index.js
  migrations/models/user.js
  package.json
Labels: dave, kenzie

#47 product card partial
  app/views/partials/product-card.pug
Labels: View, feature, jordan

#50 Kb products by type
  app/controllers/categoryCtrl.js
  app/controllers/productTypesCtrl.js
  app/models/product.js
  app/routes/index.js
  app/views/category.pug
  app/views/partials/product-card.pug
  app/views/product-type.pug
Labels: jordan

#53 Kb search
  app/controllers/searchCtrl.js
  app/routes/index.js
  app/views/partials/nav.pug
  app/views/search.pug
Labels: dave, jordan

#55 Authentication Route
  app/controllers/manageProductsCtrl.js
  app/routes/checkAuth.js
  app/routes/index.js
  app/routes/productsRouter.js
Labels: david, kenzie

#57 Dh view prod types
  app/controllers/productTypesCtrl.js
  app/models/producttype.js
  app/routes/index.js
  app/views/index.pug
  app/views/partials/allProductTypes.pug
  app/views/product.pug
  data/json/productTypes.json
  data/json/products.json
Labels: david, kenzie

#59 dynamic categories in nav
  app/controllers/cartCtrl.js
  app/routes/index.js
  app/views/partials/nav.pug
Labels: jordan, melissa

#61 Manage Products View/'Delete' Product
  app/client/front-end.js
  app/controllers/manageProductsCtrl.js
  app/controllers/productDetailCtrl.js
  app/models/index.js
  app/routes/productsRouter.js
  app/views/index.pug
  app/views/layout.pug
  app/views/manage-products.pug
  app/views/partials/product-card.pug
  package.json
Labels: dave, jordan

#67 Customer's settings view
  app/controllers/managePaymentsCtrl.js
  app/controllers/settingsCtrl.js
  app/routes/index.js
  app/views/settings.pug
Labels: feature, kenzie, melissa

#68 Refactored prodTypes controller
  app/controllers/productTypesCtrl.js
  app/routes/index.js
  app/views/partials/allProductTypes.pug
Labels: bug, feature, jordan, melissa

#71 Closing Orders
  app/controllers/cartCtrl.js
  app/controllers/completeOrderCtrl.js
  app/routes/cartRouter.js
  app/routes/index.js
  app/views/cart.pug
  app/views/complete-order.pug
  app/views/order-confirmation.pug
Labels: david, kenzie

#73 Styling! Buttons working!
  app/client/front-end.js
  app/controllers/authCtrl.js
  app/controllers/cartCtrl.js
  app/views/cart.pug
  app/views/index.pug
  app/views/layout.pug
  app/views/manage-payments.pug
  app/views/manage-products.pug
  app/views/partials/nav.pug
  app/views/partials/product-card.pug
  app/views/product-type.pug
  app/views/settings.pug
  app/views/welcome.pug
Labels: feature, jordan, kenzie

#75 delete from cart
  app/client/front-end.js
  app/controllers/cartCtrl.js
  app/routes/authRoute.js
  app/routes/cartRouter.js
  app/routes/index.js
  app/views/partials/product-card.pug
Labels: david, feature, jordan

#81 product types don't show products that are sold out
  app/controllers/productTypesCtrl.js
Labels: bug, david, jordan

#82 Fixes #77: account_number is now a string
  app/models/paymentoption.js
  app/views/new-payment-option.pug
Labels: bug, dave, kenzie

#83 changed product types data to avoid duplicates
  app/views/product-type.pug
  data/faker/_productTypesFaker.js
  data/faker/index.js
  data/json/productTypes.json
Labels: dave, enhancement, melissa

#85 cleaned up router files stylistically, mvoed adddToCart to cart ctrl/route
  app/client/front-end.js
  app/controllers/cartCtrl.js
  app/controllers/productDetailCtrl.js
  app/routes/authRoute.js
  app/routes/cartRouter.js
  app/routes/checkAuth.js
  app/routes/index.js
  app/routes/paymentsRouter.js
  app/routes/productsRouter.js
  app/views/product-details.pug
Labels: dave, enhancement, melissa, refactor

#86 /cart displays appropriate message for deleting products from cart
  app/client/front-end.js
  app/controllers/cartCtrl.js
Labels: bug, dave, kenzie

#88 Editing Customer Data
  app/controllers/settingsCtrl.js
  app/models/customer.js
  app/routes/index.js
  app/routes/settingsRouter.js
  app/views/edit-settings.pug
  app/views/login.pug
  app/views/partials/user-form.pug
  app/views/settings.pug
Labels: david, kenzie

#87 Add Prod Form Validation
  app/controllers/manageProductsCtrl.js
  app/models/product.js
  app/views/new-product.pug
Labels: jordan, kenzie

#89 Fixes #7: Prints user's products with quantity remaining, sold
  app/views/partials/product-card.pug
Labels: kenzie, melissa

#92 fixed data gen
  data/build-data.js
Labels: bug, jordan, melissa

#91 Kb order history
  app/controllers/settingsCtrl.js
  app/routes/index.js
  app/views/order-history.pug
  app/views/settings.pug
Labels: enhancement, jordan, melissa

#94 remove creation_date and account_creation_date
  app/controllers/manageProductsCtrl.js
  app/models/customer.js
  app/models/order.js
  app/models/product.js
  data/faker/_customersFaker.js
  data/faker/_ordersFaker.js
  data/faker/_productsFaker.js
  data/json/customers.json
  data/json/orders.json
  data/json/paymentOptions.json
  data/json/productOrders.json
  data/json/products.json
  migrations/20180419145202-create-customer.js
  migrations/20180419145403-create-product.js
  migrations/20180419151440-create-order.js
Labels: bug, jordan, melissa

#95 Display latest products on homepage
  app/controllers/homepageCtrl.js
  app/routes/index.js
  app/views/index.pug
Labels: david, kenzie

#96 Fixes #12: Users can recommend products to one another
  app/client/front-end.js
  app/controllers/productDetailCtrl.js
  app/controllers/recommendationCtrl.js
  app/models/customer.js
  app/models/product.js
  app/routes/index.js
  app/routes/productsRouter.js
  app/views/partials/nav.pug
  app/views/partials/product-card.pug
  app/views/product-details.pug
  app/views/recommendations.pug
Labels: feature, jordan, kenzie

#98 Fixes #1 Cancel Order
  app/client/front-end.js
  app/controllers/cartCtrl.js
  app/models/order.js
  app/routes/cartRouter.js
  app/views/cart.pug
  data/json/customers.json
  data/json/orders.json
  data/json/paymentOptions.json
  data/json/productOrders.json
  data/json/products.json
Labels: david, kenzie

#97 Dh style
  app/app.js
  app/static/css/main.css
  app/views/layout.pug
  app/views/product-details.pug
Labels: kenzie, melissa
